# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{nixpkgs}: { config, lib, pkgs, ... }:

{
  imports =
    [ nixpkgs.nixosModules.notDetected
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9aa8091d-7153-4524-b937-dd8adfdbaea9";
      fsType = "ext4";
    };

  fileSystems."/mnt/gentoo" =
    { device = "/dev/disk/by-uuid/335db3ee-710f-4c98-ab89-ee871dd56d31";
      fsType = "ext4";
    };

  fileSystems."/mnt/share" =
    { device = "/dev/disk/by-uuid/760faa93-2b9e-40fc-bb1b-66c5f04cebb8";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = "powersave";
}
