# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  qmk_firmware = {
    pname = "qmk_firmware";
    version = "2f50d1ed03058f69d7aeddaae34eb07673f3f9e8";
    src = fetchFromGitHub ({
      owner = "zsa";
      repo = "qmk_firmware";
      rev = "2f50d1ed03058f69d7aeddaae34eb07673f3f9e8";
      fetchSubmodules = true;
      sha256 = "sha256-HzSJu2aSxgZMRVBOy0wjW/AQOiil372D3+KUD0Ya2Wc=";
    });
  };
}
