#! @bash@/bin/bash
fixsettings () {
    PATH="@dbus@/bin${PATH:+:$PATH}" @dunst@/bin/dunstctl set-paused false
    @xorg.xset@/bin/xset dpms 0 0 600
    @systemd@/bin/systemctl --user start passphrases.service
}
cleanquit () {
    fixsettings
    kill %1
}
trap cleanquit HUP INT TERM
@i3lock@/bin/i3lock -n -i /mnt/persist/tejing/wallpapers/lockscreen.png &
PATH="@dbus@/bin${PATH:+:$PATH}" @dunst@/bin/dunstctl set-paused true
@xorg.xset@/bin/xset dpms 0 0 15
@systemd@/bin/systemctl --user stop passphrases.service
while ! wait;do true;done
fixsettings
