# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/98d52540-e5ea-41ee-b012-300cb3424aae";
      fsType = "btrfs";
      options = [ "subvol=root/current" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/98d52540-e5ea-41ee-b012-300cb3424aae";
      fsType = "btrfs";
      options = [ "subvol=home/current" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/98d52540-e5ea-41ee-b012-300cb3424aae";
      fsType = "btrfs";
      options = [ "subvol=boot" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/98d52540-e5ea-41ee-b012-300cb3424aae";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/mnt/system" =
    { device = "/dev/disk/by-uuid/98d52540-e5ea-41ee-b012-300cb3424aae";
      fsType = "btrfs";
    };

  fileSystems."/share" =
    { device = "/dev/disk/by-uuid/2bba2a0d-02f8-4243-a139-4c02b5681754";
      fsType = "btrfs";
      options = [ "subvol=share" ];
    };

  fileSystems."/mnt/persist" =
    { device = "/dev/disk/by-uuid/2bba2a0d-02f8-4243-a139-4c02b5681754";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3279-FFF8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
