# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  qmk_firmware = {
    pname = "qmk_firmware";
    version = "c2008634f8996340c7eb8e95d640a20e37228089";
    src = fetchFromGitHub {
      owner = "zsa";
      repo = "qmk_firmware";
      rev = "c2008634f8996340c7eb8e95d640a20e37228089";
      fetchSubmodules = true;
      sha256 = "sha256-ZuyxzUy6ePg/1zMQi1IxU9xpF8EdAEnCQfI7OqIOQxA=";
    };
    date = "2023-12-21";
  };
}
