# NOTE: this file was generated by the Mobile NixOS installer.
{ config, lib, pkgs, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/71822da3-1035-4079-8921-bd1204d2400d";
      fsType = "ext4";
    };
    "/mnt/sdcard" = {
      device = "/dev/disk/by-uuid/e411f832-c97c-4a33-8ecc-829b43012399";
      fsType = "ext4";
    };
  };

  boot.initrd.luks.devices = {
    "LUKS-TEJINGPHONE-ROOTFS" = {
      device = "/dev/disk/by-uuid/4bcab0bf-711e-4d78-a412-a5b8ac5801bb";
    };
    "LUKS-TEJINGPHONE-SDCARD" = {
      device = "/dev/disk/by-uuid/7d455c88-5e4f-46a6-bc62-7d0006277727";
    };
  };

  nix.settings.max-jobs = lib.mkDefault 3;
  nixpkgs.hostPlatform = "aarch64-linux";
}
