#! @bash@/bin/bash

dir="/run/user/$(id -u)/myi3exit"
stamp="$dir/stamp"
tempstamp="$dir/tempstamp"
mkdir -p "$dir"
touch -d '2 sec ago' "$tempstamp"
if test "$stamp" -nt "$tempstamp"; then
    @i3@/bin/i3-msg exit
else
    touch "$stamp"
fi
rm "$tempstamp"
